### ISSUE TITLE
Subscribe button w/ Klaviyo integration

### ISSUE THREAD

**Issue by Gallred** [tksventures/tokes-landingpage#1]
We need a way to get users added to an email list - GDA will be taking this over and using it as one point of our IEO sales funnel.

We are now using Klaviyo - https://www.klaviyo.com

I have added Jacob as an admin - @bravetarget , it should be in your Tokes email.

You will need to create a snippet via "Signup Forms"

I'd like each page to redirect to a separate segment, one per website (multichain, tokes, eden, cubed, etc.)

Similar issue:
tksventures/mv-landingpage#3 (comment)
tksventures/cubed-landingpage#3 (comment)
https://github.com/tksventures/eden-landingpage/issues/3#issue-500485242

**Comment by bunthius** [comment]
![image.png](https://images.zenhubusercontent.com/5c128a7da43e9647e63a8de1/671c6f4a-c3c0-480f-8fc0-0adb1610c1d4)
